FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt flask boto3

COPY src/ ./src/

ENV MIDDLEWARE_HOST=0.0.0.0
ENV MIDDLEWARE_PORT=8001

EXPOSE 8001

CMD ["python", "-m", "src.server"]
